### ISSUE TITLE
How to run this project? And does it still work?

### ISSUE THREAD

**Issue by gurmeetsinghmalhotra** [stewartmcgown/grammarly-api#14]
I am a seasoned PHP developer and have absolutely no idea how node projects run. Can you please provide steps/instructions about how I can run this project after cloning it. I did npm run build and I see

```
nps is executing `build` : nps build.prebuild && tsc -p tsconfig.build.json
nps is executing `build.prebuild` : node node_modules/rimraf/bin.js ./build 
```

What's after this? How do I actually see the errors or the error object?
**Also, does this project still run as tests are failing**

**Comment by stewartmcgown** [comment]
Well you've successfully built it, so you run the compiled JS file using
`node build/{filename}.nd`

**Comment by gurmeetsinghmalhotra** [comment]
@stewartmcgown Thanks for the quick reply.

I was able to run the project after I added your lib in an existing nextjs project as an npm dependency.
Another mistake which I was making was using
`import { correct, Grammarly, plagiarism } from 'grammarly-api';`
instead of 
`import { correct, Grammarly, plagiarism } from '@stewartmcgown/grammarly-api';`

Although I would still like to know if I run it as a standalone application as you mentioned we can do
`node build/{filename}.nd`
What is {filename}? Do I have to manually create a file inside build and add its name here? Or what it is as my build contains 2 files index.js, index.d.ts and a lib folder.
Please guide if you have some time.

PS: Thanks for creating this wonderful lib as if it hadn't worked I would have most probably dropped the feature which I am implementing. 👍

**Comment by stewartmcgown** [comment]
I meant .js, so node build/index.js. there are better guides out there on how to write a node app!
