### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by Edude42** [stewartmcgown/grammarly-api#4]
I love this API. It works great and does exactly what I want. Additionally, it is the only API that doesn't mess with the casing of words. My one big issue is that it takes at least 3 seconds to make a request. Is this Grammarly's fault? Is there any way to improve this?

**Comment by stewartmcgown** [comment]
look at the code, there is like 0 overhead. grammarly is just slow.

if you've ever used their editor you'll wait for the same three seconds to get results
